[package]
name = "rustc_codegen_nvvm"
version = "0.1.0"
authors = ["Riccardo D'Ambrosio <rdambrosio016@gmail.com>", "The Rust Project Developers"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["dylib"]

[dependencies]
nvvm = { version = "0.1", path = "../nvvm" }
rustc-demangle = "0.1.20"
libc = "0.2.97"
tar = "0.4.35"
once_cell = "1.8.0"
bitflags = "1.3.2"
tracing = "0.1.29"
find_cuda_helper = { path = "../find_cuda_helper" }

[build-dependencies]
build-helper = "0.1.1"
cc = { version = "1.0", features = ["parallel"] }

[package.metadata.rust-analyzer]
rustc_private = true
